# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pingpong.proto',
  package='pingpong',
  syntax='proto3',
  serialized_pb=_b('\n\x0epingpong.proto\x12\x08pingpong\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\nPingponger\x12\x37\n\x04Ping\x12\x15.pingpong.PingRequest\x1a\x16.pingpong.PongResponse\"\x00\x62\x06proto3')
)




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='pingpong.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pingpong.PingRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_PONGRESPONSE = _descriptor.Descriptor(
  name='PongResponse',
  full_name='pingpong.PongResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pingpong.PongResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PongResponse'] = _PONGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'pingpong_pb2'
  # @@protoc_insertion_point(class_scope:pingpong.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

PongResponse = _reflection.GeneratedProtocolMessageType('PongResponse', (_message.Message,), dict(
  DESCRIPTOR = _PONGRESPONSE,
  __module__ = 'pingpong_pb2'
  # @@protoc_insertion_point(class_scope:pingpong.PongResponse)
  ))
_sym_db.RegisterMessage(PongResponse)



_PINGPONGER = _descriptor.ServiceDescriptor(
  name='Pingponger',
  full_name='pingpong.Pingponger',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=90,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='pingpong.Pingponger.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PONGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PINGPONGER)

DESCRIPTOR.services_by_name['Pingponger'] = _PINGPONGER

# @@protoc_insertion_point(module_scope)
